#!/bin/bash
# ############################################################################
# EXECUTABLE: install-deps.sh                                                #
# PACKAGE: just-bashit version 0.1.4                                         #
# ############################################################################
set -euo pipefail
IFS=$'\n\t'

DRY_RUN=0
VERBOSE=0
SECTION_OVERRIDE=""
GROUPS_STR="runtime"
TEMPLATE=0
TEMPLATE_PATH="-"

read -r -d '' HELP <<-'EOF' || true
	Usage: install-deps.sh [OPTIONS] [DEPS_FILE]

	  Install system packages for the detected OS from a TOML deps file.
	  Input resolution order: DEPS_FILE arg > jb-deps.toml in CWD > stdin.

	  Sections are grouped by purpose and package manager:

	    [runtime.apt]
	    packages = ["libzmq3-dev", "libfftw3-dev"]

	    [dev.apt]
	    packages = ["build-essential", "cmake"]

	    [runtime.pacman]
	    packages = ["zeromq", "fftw"]

	  Supported package managers: apt, pacman, brew, dnf, zypper, apk, msys2.

	Options:
	  -h / --help              Show this message and exit.
	  -n / --dry-run           Print the install command without executing.
	  -v / --verbose           Print section, groups, and package list before acting.
	  -s / --section SECTION   Override auto-detected package manager.
	  -g / --groups  GROUP     Comma-separated groups to install (default: runtime).
	                           E.g. --groups runtime,dev installs both.
	       --template [PATH]   Write a scaffold deps.toml to PATH (default: stdout).

	Arguments:
	  DEPS_FILE  Path to TOML deps file. Omit to read from stdin or auto-discover jb-deps.toml.
EOF

# ---------------------------------------------------------------------------
# Argument parsing — manual loop to support both short and long options.
# ---------------------------------------------------------------------------
DEPS_FILE=""
while [[ $# -gt 0 ]]; do
	case "$1" in
	-h | --help)
		echo "${HELP}"
		exit 0
		;;
	-n | --dry-run)
		DRY_RUN=1
		shift
		;;
	-v | --verbose)
		VERBOSE=1
		shift
		;;
	-s | --section)
		SECTION_OVERRIDE="${2:?Option $1 requires an argument.}"
		shift 2
		;;
	-g | --groups)
		GROUPS_STR="${2:?Option $1 requires an argument.}"
		shift 2
		;;
	--template)
		TEMPLATE=1
		if [[ $# -gt 1 && "${2}" != -* ]]; then
			TEMPLATE_PATH="${2}"
			shift 2
		else
			TEMPLATE_PATH="-"
			shift
		fi
		;;
	-*)
		echo "Invalid option: $1"
		echo "${HELP}"
		exit 1
		;;
	*)
		DEPS_FILE="$1"
		shift
		;;
	esac
done

# ---------------------------------------------------------------------------
# _log: print to stderr when verbose is on.
# ---------------------------------------------------------------------------
_log() { [[ ${VERBOSE} -eq 1 ]] && echo "$*" >&2 || true; }

# ---------------------------------------------------------------------------
# _template: emit a scaffold deps.toml to stdout or a file.
# ---------------------------------------------------------------------------
_template() {
	local dest="${1}"
	local content
	content=$(
		cat <<'TOML'
# deps.toml — project system dependencies
# Generated by install-deps.sh --template
#
# Usage:
#   install-deps.sh deps.toml              # runtime only
#   install-deps.sh -g dev deps.toml       # dev/build tools
#   install-deps.sh -g runtime,dev deps.toml
#
# Remove sections for package managers you don't support.
# Use jbx install-deps

[runtime.apt]
packages = [
    # e.g. "libzmq3-dev",
]

[runtime.pacman]
packages = [
    # e.g. "zeromq",
]

[runtime.brew]
packages = [
    # e.g. "zeromq",
]

[runtime.dnf]
packages = [
    # e.g. "zeromq-devel",
]

[runtime.zypper]
packages = [
    # e.g. "zeromq-devel",
]

[runtime.apk]
packages = [
    # e.g. "zeromq-dev",
]

[runtime.msys2]
packages = [
    # e.g. "mingw-w64-ucrt-x86_64-zeromq",
]

[dev.apt]
packages = [
    # e.g. "build-essential",
]

[dev.pacman]
packages = [
    # e.g. "base-devel",
]

[dev.brew]
packages = [
    # e.g. "cmake",
]

[dev.dnf]
packages = [
    # e.g. "gcc", "cmake",
]

[dev.zypper]
packages = [
    # e.g. "gcc", "cmake",
]

[dev.apk]
packages = [
    # e.g. "build-base", "cmake",
]

[dev.msys2]
packages = [
    # e.g. "mingw-w64-ucrt-x86_64-gcc",
]
TOML
	)
	if [[ "${dest}" == "-" ]]; then
		echo "${content}"
	else
		echo "${content}" >"${dest}"
		echo "wrote ${dest}" >&2
	fi
}

# ---------------------------------------------------------------------------
# _detect_section: infer the package manager from the running OS.
# ---------------------------------------------------------------------------
_detect_section() {
	local os
	os="$(uname -s)"
	case "${os}" in
	Darwin)
		echo "brew"
		return
		;;
	Linux)
		local ID="" ID_LIKE=""
		if [ -f /etc/os-release ]; then
			# shellcheck source=/dev/null
			. /etc/os-release
		fi
		case "${ID_LIKE:-} ${ID:-}" in
		*debian* | *ubuntu*) echo "apt" ;;
		*arch* | *cachyos* | *manjaro*) echo "pacman" ;;
		*fedora* | *rhel* | *centos* | *rocky* | *alma*) echo "dnf" ;;
		*suse*) echo "zypper" ;;
		*alpine*) echo "apk" ;;
		*)
			echo "error: unrecognized Linux distro (ID='${ID}' ID_LIKE='${ID_LIKE}')" >&2
			echo "       Use --section to specify a package manager." >&2
			exit 1
			;;
		esac
		;;
	MINGW* | MSYS* | CYGWIN*)
		echo "msys2"
		;;
	*)
		echo "error: unsupported OS '${os}'" >&2
		exit 1
		;;
	esac
}

# ---------------------------------------------------------------------------
# _parse_section: extract packages from a [group.section] TOML header.
# Handles both multiline and inline array syntax. Input via stdin.
# ---------------------------------------------------------------------------
_parse_section() {
	local group="$1" section="$2"
	local target="[${group}.${section}]"
	awk -v target="${target}" '
		/^\[/ {
			in_s = ($0 == target)
			in_l = 0
			next
		}
		in_s && /packages[[:space:]]*=/ {
			in_l = 1
			s = $0
			sub(/.*packages[[:space:]]*=[[:space:]]*\[/, "", s)
			if (index(s, "]") > 0) { sub(/\].*/, "", s); in_l = 0 }
			n = split(s, a, "\"")
			for (i = 2; i <= n; i += 2) if (a[i] != "") print a[i]
			next
		}
		in_l && /\]/ {
			s = $0
			sub(/\].*/, "", s)
			n = split(s, a, "\"")
			for (i = 2; i <= n; i += 2) if (a[i] != "") print a[i]
			in_l = 0
			next
		}
		in_l {
			n = split($0, a, "\"")
			for (i = 2; i <= n; i += 2) if (a[i] != "") print a[i]
		}
	'
}

# ---------------------------------------------------------------------------
# _do_install: run or print the install command for the detected section.
# ---------------------------------------------------------------------------
_do_install() {
	local section="$1"
	shift
	case "${section}" in
	apt)
		if [ "${DRY_RUN}" -eq 1 ]; then
			echo "sudo apt-get update"
			(
				IFS=' '
				echo "sudo apt-get install -y --no-install-recommends $*"
			)
			return
		fi
		sudo apt-get update
		sudo apt-get install -y --no-install-recommends "$@"
		;;
	pacman)
		if [ "${DRY_RUN}" -eq 1 ]; then
			(
				IFS=' '
				echo "sudo pacman -Sy --needed --noconfirm $*"
			)
			return
		fi
		sudo pacman -Sy --needed --noconfirm "$@"
		;;
	brew)
		if [ "${DRY_RUN}" -eq 1 ]; then
			(
				IFS=' '
				echo "brew install $*"
			)
			return
		fi
		brew install "$@"
		;;
	dnf)
		if [ "${DRY_RUN}" -eq 1 ]; then
			(
				IFS=' '
				echo "sudo dnf install -y $*"
			)
			return
		fi
		sudo dnf install -y "$@"
		;;
	zypper)
		if [ "${DRY_RUN}" -eq 1 ]; then
			(
				IFS=' '
				echo "sudo zypper install -y $*"
			)
			return
		fi
		sudo zypper install -y "$@"
		;;
	apk)
		if [ "${DRY_RUN}" -eq 1 ]; then
			(
				IFS=' '
				echo "sudo apk add $*"
			)
			return
		fi
		sudo apk add "$@"
		;;
	msys2)
		# msys2 is Windows — always print instructions, never run.
		echo "Windows/MSYS2: open a UCRT64 shell and run:"
		(
			IFS=' '
			echo "  pacman -S $*"
		)
		exit 0
		;;
	*)
		echo "error: unknown section '${section}'" >&2
		exit 1
		;;
	esac
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if [[ ${TEMPLATE} -eq 1 ]]; then
	_template "${TEMPLATE_PATH}"
	exit 0
fi

# Slurp deps content: explicit file > jb-deps.toml in CWD > stdin.
if [ -n "${DEPS_FILE}" ]; then
	CONTENT=$(cat "${DEPS_FILE}")
elif [ -f "jb-deps.toml" ]; then
	CONTENT=$(cat "jb-deps.toml")
else
	CONTENT=$(cat)
fi

SECTION="${SECTION_OVERRIDE:-$(_detect_section)}"

# Collect packages across all requested groups (comma-separated).
PACKAGES=()
mapfile -t _GROUPS < <(tr ',' '\n' <<<"${GROUPS_STR}")
for _group in "${_GROUPS[@]}"; do
	mapfile -t _pkgs < <(echo "${CONTENT}" | _parse_section "${_group}" "${SECTION}")
	PACKAGES+=("${_pkgs[@]+"${_pkgs[@]}"}")
done
unset _GROUPS _pkgs _group

if [ "${#PACKAGES[@]}" -eq 0 ]; then
	echo "error: no packages found for group(s) '${GROUPS_STR}' section '${SECTION}' in deps file" >&2
	exit 1
fi

_log "section:  ${SECTION}"
_log "groups:   ${GROUPS_STR}"
(
	IFS=' '
	_log "packages: ${PACKAGES[*]}"
)

_do_install "${SECTION}" "${PACKAGES[@]}"
